update README: require NativeModules
fixes unit testing with jest (otherwise you get `Error: Cannot find module 'NativeModules' `)

copied from here: https://github.com/smore-inc/react-native-segment-io-analytics/issues/3
````
All require statements for React Native modules should go through the public interface:
// This may pull in an unexpected version of `RCTDeviceEventEmitter` and `NativeModules`
var RCTDeviceEventEmitter = require('RCTDeviceEventEmitter');
var RNKeyboardEventsManager = require('NativeModules').RNKeyboardEventsManager
becomes

// This will ensure that you require the correct modules, via the react-native package
var {
  DeviceEventEmitter,
  NativeModules: {
    RNKeyboardEventsManager,
  },
} = require('react-native');
````
https://github.com/facebook/react-native/releases/tag/v0.7.0-rc